### ISSUE TITLE
docker image's docker-asciidoctor failing to talking to https based confluence server

### ISSUE THREAD

**Issue by itsme-narahari** [asciidoctor/docker-asciidoctor#119] opened 2019-12-21 15:45 UTC
#### asciidoctor-confluence SSL issues ####
Friends:

Thank you in advance for your time and attention.

I am trying to use the docker image for asciidoctor, specifically the *asciidoctor-confluence*.

I tried the following
```
HOST=https://conf.es.ak.azz.com
SPACEKEY=MDRD
TITLE="First Test"
USERNAME=zulu
PASSWORD=zebra

docker run -it -v $(pwd):/documents/ asciidoctor/docker-asciidoctor
asciidoctor-confluence --host $HOST --spaceKey $SPACEKEY --title $TITLE
--username $USERNAME --password $PASSWORD adoc_tester.adoc
``` 

### When I ran this I saw the following error. ###

```
An error occurred, the page has not been created because:
SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
```

I did some research it looks like the https related libraries are not baked in for **https** end points specfically the **SSL V3** is not available inside the image.

Can I get some help on how to solve it or the docker image be upgraded to use SSL3 ?

Thank you once again for your time and attention.

-Narahari

**Comment by dduportal** [comment] 2019-12-24 13:40
Hi @itsme-narahari , what is the result of the following command?

```bash
docker run -it asciidoctor/docker-asciidoctor curl -v -L -sS https://conf.es.ak.azz.com -o /dev/null
```

?

**Comment by itsme-narahari** [comment] 2019-12-28 16:35
So sorry that I took this much time to get back.

Please see below.
========================

> docker run -it asciidoctor/docker-asciidoctor curl -v -L -sS https://conf.es.ak.azz.com -o /dev/null

The output is
```docker run -it asciidoctor/docker-asciidoctor curl -v -L -sS https://conf.es.ak.azz.com -o /dev/null
*   Trying 19.15.8.128::443...
* TCP_NODELAY set
* Connected to conf.es.ak.azz.com (19.15.8.128:) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to conf.es.ak.azz.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to conf.es.ak.azz.com:443
```

**Comment by dduportal** [comment] 2019-12-28 17:43
Ok thanks. Can you know try the following commands please (I cannot reproduce on my own, so I need your help).?

```bash
docker run -it asciidoctor/docker-asciidoctor sh -c "apk add --no-cache openssl && curl -v -L -sS https://conf.es.ak.azz.com -o /dev/null"
```
,
```bash
docker run -it asciidoctor/docker-asciidoctor sh -c "apk add --no-cache openssl && openssl s_client -connect conf.es.ak.azz.com:443  -servername conf.es.ak.azz.com"
```

and

```bash
docker run -it asciidoctor/docker-asciidoctor sh -c "apk add --no-cache libressl && curl -v -L -sS https://conf.es.ak.azz.com -o /dev/null"
```

?

**Comment by itsme-narahari** [comment] 2019-12-28 21:38
##### Thank you for your time and help on this issue.  It means a lot. #####
What I have done, I shelled into the container and ran the commands individually, **_one step at a time_**

>[nlakshmi@ROSE02T44GUH03Q adoc_files]$ docker run --rm -it asciidoctor/docker-asciidoctor bash`

Command number **one** inside the container

` bash-5.0# SERVER_NAME=confluence.es.ad.adp.com`

`bash-5.0# apk add --no-cache openssl && curl -v -L -skS https://${SERVER_NAME} -o /dev/null`

The output of the **first** command is the following

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/1) Installing openssl (1.1.1d-r2)
Executing busybox-1.30.1-r2.trigger
OK: 224 MiB in 114 packages
*   Trying 11.6.8.134:443...
* TCP_NODELAY set
* Connected to confluence.es.ad.adp.com (11.6.8.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to confluence.es.ad.adp.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to confluence.es.ad.adp.com:443
```

Command number **two** inside the container

`bash-5.0# apk add --no-cache openssl && openssl s_client -connect ${SERVER_NAME}:443  -servername ${SERVER_NAME}`

The output of the **second** command is the following

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
OK: 224 MiB in 114 packages
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 326 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
bash-5.0#
```

Command number **three** inside the container

`bash-5.0# apk add --no-cache libressl && curl -v -L -skS https://${SERVER_NAME} -o /dev/null`

The output of the **third** command is the following

```fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libressl2.7-libcrypto (2.7.5-r0)
(2/4) Installing libressl2.7-libssl (2.7.5-r0)
(3/4) Installing libressl2.7-libtls (2.7.5-r0)
(4/4) Installing libressl (2.7.5-r0)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 227 MiB in 118 packages
*   Trying 11.6.8.134:443...
* TCP_NODELAY set
* Connected to confluence.es.ad.adp.com (11.6.8.134) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to confluence.es.ad.adp.com:443
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to confluence.es.ad.adp.com:443
bash-5.0#
```

**Comment by dduportal** [comment] 2020-01-03 11:39
Hi @itsme-narahari , thanks for the feedback. Next time, can you try the commands as I give it to you? The reason is that each command can be influenced by the previous one, hence running the 3 commands is separated containers to ensure isolation.

However I got more understanding here. it looks like that the Confluence server you are using is not correctly configured for the full TLS 1.3 certificates, as no "SNI" is sent (openssl command).

- Is the server using a self-signed certificate?
- Is the server using another TLS/SSL protocol than TLS v1.2 or TLS 1.3 ? I see that you mentionned "SSLv3" which is unsecure and not recommended (default curl and wget does not support it anymore)?
- Do you have a situation (another container, another VM) where you it works well for you and where you can run the same command (only the "curl" and "openssl" command, not the "docker run") ? So we can compare outputs and ensure it's not specific to Alpine Linux?

**Comment by dduportal** [comment] 2020-07-20 08:03
Closing as there were no answer from the author after a few months.

Please feel free to reopen if you have more comments or still facing the issue.

**Closed by dduportal** 2020-07-20 08:03 UTC
