### ISSUE TITLE
Use Alpine Docker image

### ISSUE THREAD

**Issue by lordofthejars** [asciidoctor/docker-asciidoctor#13] opened 2015-05-30 17:02 UTC
I have seen that currently you are using fedora docker image. This is a huge image which maybe the 90% of the size is of unused things. I recommend use Alpine image http://gliderlabs.viewdocs.io/docker-alpine In terms of Dockerfile it requires more instructions, but the image only uses 5Mb, which I think that for an Asciidoctor image (which you want it to render documents), it is the perfect one.

**Comment by gscheibel** [comment] 2015-06-01 08:59
I used Fedora at the first place because according to @mojavelinux using it we could be quoted into a (Fedora) magazine.
Therefore I would prefer to switch to a smaller to. I'll have a look at the Alpine image.
Thanks for the info.

**Comment by mojavelinux** [comment] 2015-06-01 09:32
Is it possible to use a smaller Fedora image? I'm not bound to Fedora, but this seems like excellent feedback for the Fedora team. Does it have to be so huge? Surely they would be motivated to make it smaller.

...having said that, I'm not opposed to other distributions if they fit requirements better.

**Comment by lordofthejars** [comment] 2015-06-01 09:37
well for me is that basically Alpine is a 5Mb distro. Sometimes you need to install some c libraries to run some software. For example in case of trying use Java you need to install glib. But overall is a good image because at least you only install what you need. Of course I have nothing against Fedora, only that I am planning to use it for Apache TomEE official image because with only 100MB you will be able to have a docker image with a Java EE Application Server ready to be used. Compare the same but for other distro like Wildfly.

**Comment by gscheibel** [comment] 2015-06-01 09:44
in our case we have to have a look a the OS package manager, at the moment
we are using yum for a lot of libs in the container.
So first for Alpine, we should probably deploy Asciidoctor (including PDF
etc) to the Alpine package manager before considering moving completely.

**Comment by lordofthejars** [comment] 2015-06-01 09:47
or install it without package manager. But yes updating Alpine PM would be the way

**Comment by gscheibel** [comment] 2015-06-01 09:48
another approach could be to have multiple container based on different OS
(fedora, ubuntu, coreOS, ....)

**Comment by ctwise** [comment] 2015-06-03 11:03
Thanks, I'll take a look at it!

**Comment by lordofthejars** [comment] 2015-06-03 11:15
Be aware with Alpine image, comes with nothing :smile: and when I say nothing I mean even no bash hehehe

**Comment by gscheibel** [comment] 2015-06-03 11:20
so you end-up with 200 lines in your dockerfile just to install the basic
OS requirements.

**Comment by lordofthejars** [comment] 2015-06-03 11:27
Probably, but well you can create several layers instead one. But the good point is that your image has only what you need.

**Comment by gscheibel** [comment] 2015-06-03 12:23
sure it's always a tradeoff between simplicity and specialisation.

**Comment by lordofthejars** [comment] 2015-06-03 12:52
Exactly currently I am trying to make one for openjdk8 for TomEE and I finished by installing bash and start running there directly.

**Comment by gscheibel** [comment] 2015-06-03 12:54
I'm really interested to have a look at the final result.
Having a general basic container (bash, curl, git, ..) could help to start
with Alpine

**Comment by cexbrayat** [comment] 2015-07-09 13:18
Using @gscheibel image (I sadly can't show you the doc I'm using), I'm running into : 

```
asciidoctor -b epub3 -r asciidoctor-epub3 -r asciidoctor-diagram -D ../dist test.adoc
/usr/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/substitutors.rb:235: [BUG] Segmentation fault at 0x007f60c97bb000
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-musl]

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0215 e:000214 CFUNC  :include?
c:0020 p:0035 s:0211 e:000210 METHOD /usr/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/substitutors.rb:235
c:0019 p:0193 s:0203 e:000202 METHOD /usr/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/substitutors.rb:104
c:0018 p:0020 s:0193 e:000192 METHOD /usr/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/substitutors.rb:150
c:0017 p:0036 s:0189 e:000188 METHOD /usr/lib/ruby/gems/2.2.0/gems/asciidoctor-1.5.2/lib/asciidoctor/abstract_block.rb:128
```

Might not be related to the image per se... But it does not happen with the fedora image...

**Comment by gscheibel** [comment] 2015-07-09 13:22
@cexbrayat do you use any particular extension ? Apparently you use diagram
but with which syntax (plantuml, ditaa, ...) ?

**Comment by cexbrayat** [comment] 2015-07-09 13:27
Yeah sorry about that : I have the error with this file with every extension and format (html, epub, pdf).
I don't have it on another files though...

**Comment by gscheibel** [comment] 2015-07-09 13:32
So it might come from a syntax you are using in this file there it passes
with the fedora based image or on our host machine right ?

**Comment by cexbrayat** [comment] 2015-07-09 13:35
Yes it works with everywhere except on the alpine image. Is it the same ruby version between the fedora image and the alpine one ?

**Comment by gscheibel** [comment] 2015-07-09 13:41
It is:
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux-musl] for Alpine
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux] for Fedora

The only difference I can see is:
(lc:UTF-8 fs:UTF-8 in:- ex:UTF-8) for Alpine
(lc:US-ASCII fs:US-ASCII in:- ex:US-ASCII) for Fedora

**Comment by gscheibel** [comment] 2015-07-09 14:32
@cexbrayat in this file which kind of diagram syntax are you using ? (found
something with Ditaa)

**Comment by cexbrayat** [comment] 2015-07-09 14:35
Yes, ditaa diagram

**Comment by gscheibel** [comment] 2015-07-09 14:41
Interesting, I get a NPE and not the seg fault you got.
Something is probably missing :/

**Comment by pepijnve** [comment] 2015-07-09 14:58
digram extension author here. This could depend on the version of the diagram extension. Older versions used RJB which could explain the segfault. Later versions spawn a JVM process using exec. There might be an NPE here if it can't locate the JVM (although there's an explicit check for that in place https://github.com/pepijnve/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/util/java_socket.rb#L45).
Is a Java runtime installed in this docker image?

**Comment by gscheibel** [comment] 2015-07-09 15:01
yes it is, in alpine we have open jdk 7 and in fedora oracle jdk 8

**Comment by pepijnve** [comment] 2015-07-09 15:06
Could you post the stack trace of the exception you're getting? I might be able to tell you more based on that.

**Comment by gscheibel** [comment] 2015-07-09 15:07
here it is: https://gist.github.com/gscheibel/b4a6afed04988c941891

**Comment by pepijnve** [comment] 2015-07-09 15:24
Ok it's not my code that's the problem :) Based on http://stackoverflow.com/questions/8109607/headless-continuous-integration-with-jenkins you're probably missing some fonts.

**Comment by gscheibel** [comment] 2015-07-09 15:27
Do you know which fonts are used by ditaa ?

**Comment by pepijnve** [comment] 2015-07-09 15:33
I'll check, but I don't think it uses any specific font. Probably just the default sans-serif one. The NPE is in getting the default font, so there probably aren't any TTF fonts installed in the docker image. Installing the dejavu ones is probably sufficient.

**Comment by gscheibel** [comment] 2015-07-09 15:38
Indeed, installing fft-dejavu solves the NPE.
I'm pushing a new version of the dockerfile and and keep trying to
reproduce the original bug.

**Comment by pepijnve** [comment] 2015-07-09 15:38
It uses the 'dialog' logical font. See http://docs.oracle.com/javase/8/docs/technotes/guides/intl/fontconfig.html for details on how that gets mapped to a physical font.

**Comment by gscheibel** [comment] 2015-07-09 16:03
@cexbrayat could you re-try with the latest ( bvyc5caem85qdswhqajwcyh
<https://registry.hub.docker.com/u/gscheibel/alpine-asciidoctor/build_id/73922/code/bvyc5caem85qdswhqajwcyh/>
 )
please ?

**Comment by cexbrayat** [comment] 2015-07-09 16:41
Tried again, same error. I don't think it's related to the diagram extension as I have the same segfault with : 

    asciidoctor -b html5 test.adoc

**Comment by gscheibel** [comment] 2015-07-09 17:28
I managed to reproduce the bug by building the complete user-manual.
Now let's dive in.

**Comment by gscheibel** [comment] 2015-07-09 17:58
Stupid question, if you're using includes how many do you have in this file
?

**Comment by cexbrayat** [comment] 2015-07-10 07:31
There’s no stupid question : I don’t have any includes in this file

**Comment by pepijnve** [comment] 2015-07-10 07:41
The process is segfaulting at https://github.com/asciidoctor/asciidoctor/blob/v1.5.2/lib/asciidoctor/substitutors.rb#L235. The only code there are calls to String#include? passing in non interpolated strings. Bizarre that that would segfault.

The only way I know of to debug this is to get a build of the ruby vm with debugging symbols, attach gdb and see where/why the segfault occurs in the native code. How is the ruby vm installed in the image? Is it the Alpine ruby package or was it installed via rvm or rbenv?

**Comment by mojavelinux** [comment] 2015-07-10 07:52
You could hack substitutors.rb to at least print the offending string. That might get us closer. It feels like an encoding issue, but I could be way off.

**Comment by mgreau** [comment] 2015-07-22 23:02
FYI even JBoss has switched from Fedora 20 to CentOS 7 for all their Docker images :) https://github.com/jboss-dockerfiles/base/commit/328f451604a917a9680516ab55297811836ee296

According to the comment, the main goal is to reduce the size for each image.

**Comment by mojavelinux** [comment] 2015-07-22 23:38
:+1: I'm in favor of using a Linux that is right-sized.

**Comment by dduportal** [comment] 2016-02-24 18:56
Was trying to move to Alpine when jumping to this issue.

Here is a PR with alpine base if you want to try and help me :)

https://github.com/asciidoctor/docker-asciidoctor/pull/24

**Comment by rochdev** [comment] 2016-04-28 00:56
If anybody is interested I've created a simpler image with only the base needed to run Asciidoctor with support for HTML, PDF, EPUB and syntax highlighting using CodeRay. It weights in at **~72mb**

https://hub.docker.com/r/rochdev/alpine-asciidoctor/

I'm pretty new to Asciidoctor so let me know what you think!

**Comment by dduportal** [comment] 2017-10-12 20:37
The PR #39 introduces a base Alpine image. I am closing this issue, feel free to re-open it if you do not agree on the resolution or want to discuss!

Thank you for contributing by raising this issue.

**Closed by dduportal** 2017-10-12 20:37 UTC
Labels: Proof of concept
