### ISSUE TITLE
Update container on DockerHub

### ISSUE THREAD

**Issue by hakandilek** [asciidoctor/docker-asciidoctor#92] opened 2019-04-07 13:59 UTC
I think the container is in good shape now with the 2.0.6 version and latest fixes.

Does it get published with Travis CI or someone has to push it?

@dduportal @cexbrayat @mojavelinux

**Comment by cexbrayat** [comment] 2019-04-08 20:00
@hakandilek I don't have any access to this, sorry. I think only @dduportal and @mojavelinux can help.

As a side note, it would probably be nice to have some kind of tag to distinguish the latest using v1 and the newest using v2 (maybe simply reference the Asciidoctor version used? Like `docker-asciidoctor@1.5.8` and `docker-asciidoctor@2.0.6`?)

**Comment by mojavelinux** [comment] 2019-04-08 20:07
I like the idea of tags, but since this image bundles so many different libraries, I don't think binding it to the Asciidoctor core version really communicates the right message. Instead, I would recommend just starting to version the Docker image independently. You could, of course, use the same major version number. But even that is more of a helpful hint than anything.

**Comment by dduportal** [comment] 2019-04-09 15:06
First analysis:

- #90 merged into master with the following commit: https://github.com/asciidoctor/docker-asciidoctor/commit/a499a167277c617e36fadc4961155c03cb7cb486
- Related build in Travis: https://travis-ci.org/asciidoctor/docker-asciidoctor/builds/517833270
- The build is composed of 3 steps:
  - Docker image is built into Travis
  - Docker image is tested into Travis
  - If the builds occurs on the branch master (or not on a pull request), then a "deploy" phase send a webhook to the DockerHub to let it build the image
- The issue come from this 3rd step, the "deploy" , which send the webhook to my image (`dduportal/docker-asciidoctor`) instead the official one. Incoming PR fixing this.

**Comment by dduportal** [comment] 2019-04-09 15:48
@mojavelinux @cexbrayat @hakandilek , I just submitted #93 to fix this behavior.

I also tried a "local" `make deploy` to ensure it works right: the latest image is now up to date:

```shell
docker pull asciidoctor/docker-asciidoctor:latest && docker run --rm -t asciidoctor/docker-asciidoctor asciidoctor --version
latest: Pulling from asciidoctor/docker-asciidoctor
Digest: sha256:2fa39ea356cd7b92078803e973b8068cf4745d706b627217217b39c1f33dac5c
Status: Image is up to date for asciidoctor/docker-asciidoctor:latest
Asciidoctor 2.0.6 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by cexbrayat** [comment] 2019-04-09 19:06
@dduportal Looks like it's fixed 👍  (as I have now failing CI jobs because they use the new image that has a regression in asciidoctor-epub3 😄 )

If anyone needs it, the previous image can still be used with `asciidoctor/docker-asciidoctor@sha256:b1268f852dfb276b2f5cefa52fdf3c2e62e86d54d264cea647ccd713c92a7e66` (that's where a proper tag would be handy).

**Closed** 2019-04-25 12:03 UTC
