### ISSUE TITLE
Missing fonts for asciidoctor-mathematical

### ISSUE THREAD

**Issue by tarikgraba** [asciidoctor/docker-asciidoctor#105] opened 2019-09-13 08:02 UTC
Hi,

Can you add the `ttf-dejavu` font package as some math symbols are not rendered concretely.

More here:
https://github.com/asciidoctor/asciidoctor-mathematical/issues/42

Thx

**Comment by dduportal** [comment] 2019-09-13 17:41
Hello, thanks for your interest! I'm closing this issue as it is a duplicate of #100 .

**Closed by dduportal** 2019-09-13 17:41 UTC
